### ISSUE TITLE
Attributi prodotti da inserire

### ISSUE THREAD

**Issue by Flavio-96** [EMAD-2019-Accenture/App#16]
Per il successo e il corretto funzionamento del sistema è fondamentale chiarire quali sono gli attributi dei prodotti che vogliamo trattare. Da ciò dipendono sia le informazioni mostrate al momento della scansione dei prodotti, sia un buon sistema di promozioni dei prodotti.

Una prima valutazione degli attributi è stata fatta e può essere visionata qui: [Bozza DB](https://github.com/EMAD-2019-Accenture/App/blob/development/DB/db.md).

**Comment by mdestefano** [comment]
Ho notato i bei punti interrogativi XD. Comunque effettivamente ci sono molte colone il cui funzionamento è oscuro. Inoltre, per alcune tra quelle che comunque tu hai giustamente segnato come utli, è difficile capire il dominio dei valori. Solo sullo sconto farei un appunto, che non sempre la promozione è uno sconto in percentuale, ma a volte tolgono una quota fissa, quindi io lascerei il campo così com'è.

**Comment by Flavio-96** [comment]
Se quei campi che ho segnato vi sembrano utili, possiamo partire da quelli e poi farci un'idea su che altro può servirci.
Modifichiamo l'md di conseguenza aggiungendo cosa vogliamo inserire.
