### ISSUE TITLE
Funzionalità: gestione carrello?

### ISSUE THREAD

**Issue by Flavio-96** [EMAD-2019-Accenture/App#17]
Si può pensare di inserire come nuova funzionalità quella della **gestione del carrello** dei prodotti. La gestione del carrello darebbe la possibilità all'utente di **monitorare i prodotti** che ha scansionato e scelto di aggiungere alla propria spesa e l'**ammontare totale** del costo dei prodotti.
L'utente trae vantaggio da questa funzionalità avendo sempre sotto occhio il costo della spesa, e anche i prodotti che deve ancora acquistare; il sistema invece si avvantaggia di questo "basket" per **proporre oggetti utili all'utente o offerte presenti**.

**Comment by mdestefano** [comment]
No a prescindere, senza nemmeno leggere

**Comment by mdestefano** [comment]
Ok, nel caso però che volessimo aggiungerla, secondo me occorre chiedere esplicitamente al cliente se vuole aggiungerla al carrello, in modo tale che possiamo essere sicuri che i prodotti sono quelli che effettivamente ha intenzione di acquistare.
