### ISSUE TITLE
Completare requisiti e stilare casi d'uso

### ISSUE THREAD

**Issue by Flavio-96** [EMAD-2019-Accenture/App#23]
Dobbiamo valutare bene se mancano alcune funzionalità o meno e se quelle che abbiamo sono effettivamente giuste per i nostri obiettivi e il nostro contesto.
In base a queste dobbiamo modellare le entity del nostro sistema

**Comment by emaiannone** [comment]
- [x] Completare requisiti
- [ ] Leggere UC
