### ISSUE TITLE
Ricerca AR

### ISSUE THREAD

**Issue by emaiannone** [EMAD-2019-Accenture/App#3]
IONIC Augmented Reality -> riguardo la realtà aumentata ho trovato questi link che potrebbero essere interessanti per gli sviluppi che dobbiamo fare:

https://www.joshmorony.com/augmented-reality-in-an-ionic-angular-pwa/
Wikitude: https://market.ionicframework.com/starters/wikitude-ionic-3-starter-app
https://forum.ionicframework.com/t/augmented-reality-for-ionic/83738

**Comment by Flavio-96** [comment]
Una libreria ottima che si potrebbe usare è  [AR.js - Augmented Reality for the Web](https://github.com/jeromeetienne/AR.js).
Bisogna valutare comunque meglio l'integrazione con cordova/capacitor
