### ISSUE TITLE
Stesura schedule di massima

### ISSUE THREAD

**Issue by emaiannone** [EMAD-2019-Accenture/App#4]
# Due: 15/10/2019

**Comment by emaiannone** [comment]
Potremmo farlo come Excel essendo uno schedule

**Comment by emaiannone** [comment]
Come strutturiamo lo schedule di massima? Cosa ci mettiamo?

**Comment by mdestefano** [comment]
Sicuramente ci dobbiamo mettere le scadenze che ci ha dato la prof, che in questo momento non ricordo. Magari da li cominciamo a ragionare.

**Comment by mdestefano** [comment]
@emaiannone perché magari non le posti così ne discutiamo?

**Comment by emaiannone** [comment]
Nelle milestone sono riportate tutte le scadenze, ma le riporto qui:

- 17.10.2019 definizione di tutte le project proposal. 

- 03.11.2019 Prototipo delle interfacce e diagramma navigazionale, schema dei casi d'uso e descrizione di pochi casi d'uso principali, class diagram delle entità.

- 08.11.2019 presentazione dell'analisi alle aziende, tutti i membri del team devono presentare  

- 06.12.2019 Primo prototipo di una funzionalità principale

- 15.01.2020 seconda release prototipo

- metà febbraio 2020 App Challenge (data da definire)

**Comment by mdestefano** [comment]
Ok quindi direi di organizzarci fino alla milestone dell' 8-11, e po lasciare le altre ancora in sospeso.

**Comment by emaiannone** [comment]
Va bene, per adesso, dato che il lavoro è poco parallelizzabile, ci lavoriamo tutti. Inoltre, appena iniziamo gli altri progetti (GPS, IV, ecc.) allora definiamo uno schedule migliore.
Oggi pomeriggio ci siete che facciamo questo schedule?

**Comment by Flavio-96** [comment]
Io definirei i tempi in cui riusciamo a stare assieme per fare il punto della situazione e dividerci il lavoro (valutare chi deve fare cosa e come va fatto orientativamente). Stabilirei anche un momento nel quale facciamo il punto preciso della situazione prima della call con l'azienda (la mattina stessa è preferibile).
Il lavoro iniziale è comune alla fine e non c'è bisogno di uno schedule rigido per i singoli task ora ... man mano che andremo avanti lo perfezioniamo in base ai nostri impegni.
Ora più che altro stabilirei dei momenti in cui parliamo di cosa e come va fatto, come detto prima.
